# Generated by Django 5.1 on 2024-08-08 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('SP', 'SOUP'), ('ST', 'STUFFED'), ('CR', 'CRISPY'), ('CO', 'COOKED'), ('OT', 'OTHER')], max_length=2)),
            ],
        ),
    ]
